import { Footer } from "@/components/Footer"
import { Header } from "@/components/Header"
import type { Metadata } from "next"
import { Plus_Jakarta_Sans, Work_Sans } from "next/font/google"
import "./globals.css"

const workSans = Work_Sans({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
  variable: "--font-work-sans"
})

const plusJakartaSans = Plus_Jakarta_Sans({
  weight: ["400", "600", "800"],
  subsets: ["latin"],
  variable: "--font-jakarta-sans"
})

export const metadata: Metadata = {
  title: "Meta Blog",
  description: "Generated by create next app"
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${workSans.variable} ${plusJakartaSans.variable} w-[100%] h-[100%] flex flex-col items-center justify-center dark:bg-secondary_800`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
