import type { Metadata } from "next"
import { Work_Sans } from "next/font/google"
import "./globals.css"

const workSans = Work_Sans({
  weight: ["300", "600", "700"],
  subsets: ["latin"],
  variable: "--font-work-sans"
})

export const metadata: Metadata = {
  title: "Meta Blog",
  description: "Generated by create next app"
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${workSans.variable}`}>{children}</body>
    </html>
  )
}
